### ISSUE TITLE
remove watch in vr option 

### ISSUE THREAD

**Issue by Dhrubaof2002** [inotia00/revanced-patches#14]
### Application

Youtube 

### Issue

.

### Patch

.

### Motivation

Mistakenly getting clicked often times

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Added in revanced-patches v2.99.0.
