### ISSUE TITLE
bug: comment write section is white.

### ISSUE THREAD

**Issue by danieloox** [inotia00/revanced-patches#15]
### Type

Cosmetic

### Bug description

Comment write secion is white and dont see any letters. in og revanced is gray. maybe change it black? :)

ss:
![20221014_222552](https://user-images.githubusercontent.com/113600273/195937807-2daff869-8830-4739-8709-8bc31d8e2a9b.jpg)

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

.

### Additional context

.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Duplicate with https://github.com/inotia00/revanced-patches/issues/13
