### ISSUE TITLE
bug: Placeholders of My Mix playlists stays after turning on hiding the lists

### ISSUE THREAD

**Issue by anil-al** [inotia00/revanced-patches#16]
### Type

Cosmetic

### Bug description

After applying the patch hiding My Mix suggestions, the placeholder of the playlists stays.

### Steps to reproduce

Turn on hiding My Mix (Playlists).
Open home tab.
Voilà! 

### Relevant log output

```shell
-
```

### Screenshots or videos

![Screenshot_20221016-160952_YT RVX](https://user-images.githubusercontent.com/101948963/196037507-7ea6738a-35f5-465f-8cc4-e3cd809f0360.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
> ### Type
> Cosmetic
> 
> ### Bug description
> After applying the patch hiding My Mix suggestions, the placeholder of the playlists stays.
> 
> ### Steps to reproduce
> Turn on hiding My Mix (Playlists). Open home tab. Voilà!
> 
> ### Relevant log output
> ```shell
> -
> ```
> 
> ### Screenshots or videos
> ![Screenshot_20221016-160952_YT RVX](https://user-images.githubusercontent.com/101948963/196037507-7ea6738a-35f5-465f-8cc4-e3cd809f0360.jpg)
> 
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new and no duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I filled out all of the requested information in this issue properly.

Since it's an `Experimental flags`, it doesn't guarantee that it will always work as intended 🤷‍♂️

**Comment by anil-al** [comment]
> Since it's an `Experimental flags`, it doesn't guarantee that it will always work as intended 🤷‍♂️

I just wanted to let you know for a future fix.  By the way, thank you. It was my request to hide these. I really appreciate your effort.

**Comment by inotia00** [comment]
> > Since it's an `Experimental flags`, it doesn't guarantee that it will always work as intended 🤷‍♂️
> 
> I just wanted to let you know for a future fix. By the way, thank you. It was my request to hide these. I really appreciate your effort.

Yes, this will be fix in the next version
