### ISSUE TITLE
feat(patch): Bringing ~back~ force-vp9-codec

### ISSUE THREAD

**Issue by Spacellary** [inotia00/revanced-patches#17]
### Application

YouTube

### Issue

Allow the user to force and pick VP9 or H264 codec playback.
This in turn enables picking above 1080p resolutions, regardless of native resolution, and is useful for some vertical videos that top at 480p without VP9.

### Patch

Vanced like force-vp9-codec. Enable with a toggle in Revanced/Extended > Video settings. Possibly with a warning about possible higher battery drain if applicable.

### Motivation

This is a very useful feature if you wanna get the best possible quality playback, specially since unless a video is very popular YouTube will only serve you crappy quality, uploads at 1440p or higher force VP9 to be used and so you can "force" YouTube to serve a decent quality version regardless of their popularity.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
From the beginning, the patch was added in [2016](https://forum.xda-developers.com/t/app-patched-youtube-for-vp9-60fps-playback-64-bit.3418216/) by TeamVanced, and now it will no longer work in 2022.

For the same reason, Revanced Team removed that feature.

**Comment by Spacellary** [comment]
@inotia00 Sorry to bring this back up, but do you see a path going forward where this could be reimplemented? Or is it just "impossible" due to changes from YouTube itself?
