### ISSUE TITLE
Can somebody explain the use of donation companion and suggested actions patch.

### ISSUE THREAD

**Issue by brucewayne2001** [inotia00/revanced-patches#20]
### Application

Revanced youtube

### Issue

the use of donation companion and suggested actions patch.

### Patch

the use of donation companion and suggested actions patch.

### Motivation

the use of donation companion and suggested actions patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
donation companion
https://t.me/revanced_extended_chat/106487

suggested actions
![suggested_action](https://user-images.githubusercontent.com/108592928/196947999-168ccd01-021d-42ee-8fa7-2312da4929d2.PNG)
