### ISSUE TITLE
bug: crashes/freezes on speed selection

### ISSUE THREAD

**Issue by johnconner122** [inotia00/revanced-patches#21]
### Type

Error at runtime

### Bug description

In revanced extended settings, app crashes after selecting default speed to Auto.

### Steps to reproduce

Go to Revanced Settings->Video Settings->Select Preferred speed to any and then select speed to Auto, app freezes.

### Relevant log output

```shell
Null
```

### Screenshots or videos

![Screenshot_20221019-184350](https://user-images.githubusercontent.com/107796137/196708962-242ab5eb-830b-4bb9-9817-2c6119780e13.png)

### Additional context

YouTube v17.39.35
revanced-cli v2.14.0
revanced-patches v2.82.3
integrations v0.51.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please check if this issue is reproduced in the build released today

**Comment by johnconner122** [comment]
It's fixed, thanks.
