### ISSUE TITLE
bug: disable swipe-control when players controls are visible not working  <title>

### ISSUE THREAD

**Issue by whatimran** [inotia00/revanced-patches#30]
### Type

Other

### Bug description

This feature disable swipe-control when players controls are visible is not working in latest patches. Please fix the issue.
![Screenshot_20221021-135300](https://user-images.githubusercontent.com/77832096/197393202-c552a1b6-5f2b-444d-ba14-6859b372f698.jpg)

### Steps to reproduce

...

### Relevant log output

```shell
...
```

### Screenshots or videos

![Screenshot_20221021-135300](https://user-images.githubusercontent.com/77832096/197393241-ab52c6ee-9519-4ae9-bb86-d4de977d57fd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
this is an old Changelog.

In the latest release, it is normal for swipe to work regardless of the visibility of the player control.

**Comment by inotia00** [comment]
Confirmed to work with commit rollback

**Comment by whatimran** [comment]
Thanks a lot.
