### ISSUE TITLE
pop-up player failing

### ISSUE THREAD

**Issue by uchihasasuke2807** [inotia00/revanced-patches#31]
### Type

Other

### Bug description

The pop-up player doesn't show the video instead it shows the description/comment or anything opened with the video but not the video. The issue persists in both landscape and portrait mode. This issue wasn't there in version 17.39.

### Steps to reproduce

1. Open any video in YouTube Revanced Extended.
2. Switch to other app or return to home screen while video playing.
3. The pop-up can be seen behaving unusually.

### Relevant log output

```shell
-
```

### Screenshots or videos

![IMG_20221024_100545](https://user-images.githubusercontent.com/108347554/197449511-362c1164-6a76-4da6-b4f9-92df0ee8b514.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is an official YouTube issue, not a ReVanced issue.
