### ISSUE TITLE
feat(patch): 

### ISSUE THREAD

**Issue by Dhrubaof2002** [inotia00/revanced-patches#33]
### Application

Discord

### Issue

The default discord for android is too bland

### Patch

Betterdiscord like implementation for discord 

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Sorry but I have no plans to provide it in the future
