### ISSUE TITLE
feat(patch): Auto switch to dark mode while video playback

### ISSUE THREAD

**Issue by kastentop2005** [inotia00/revanced-patches#37]
### Application

YouTube

### Issue

Recently, YouTube has updated their UI and introduced the ambient mode. It looks dope, but the issue is that it's not working in light mode

### Patch

The patch must automatically switch to dark mode if light mode is enabled (prefferably to do so ONLY on video page)

### Motivation

For sleek design lovers it's a must have

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is the Youtube server side issue (New layout depends on the server side)

In normal cases, these issues do not occur in new layouts.

Delete the RVX app data and make sure that the issue is reproduced.
