### ISSUE TITLE
Fullscreen panels in new layout 

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/revanced-patches#38]
![Screenshot_20221027_162232_app rvx android youtube](https://user-images.githubusercontent.com/107951133/198523943-fb974730-57e1-4d95-bcef-87267c47d3b8.jpg)
![Screenshot_20221027_162232_app rvx android youtube](https://user-images.githubusercontent.com/107951133/198524042-1102b220-691a-49d4-a5c3-c80f0f4f8a7b.jpg)
### Type

Other

### Bug description

Hide fullscreen panels doesn't work on the new layout

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20221027_162232_app rvx android youtube](https://user-images.githubusercontent.com/107951133/198523943-fb974730-57e1-4d95-bcef-87267c47d3b8.jpg)

### Solution

Can you please fix that peoblem

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
I can't check the screenshot
Please upload the screenshot again

**Comment by Mohammed1520** [comment]
I have uploaded screenshot

**Comment by inotia00** [comment]
no.. it is normal for this to be displayed

Because the name of the setting is `Hide Fullscreen Button Container`, not `Hide Fullscreen Panels`.

It simply hides the button container at the bottom of the full screen.
It's a bit different from the `hide-fullscreen-panels` patch provided by ReVanced official.

So... this is normal.

**Comment by Mohammed1520** [comment]
I wish this will be fixed in upcoming releases of revanced extended and Thank you for your great efforts sir

**Comment by inotia00** [comment]
bruh.. once again mention, this is not a bug.
