### ISSUE TITLE
Patch Rqst for Amoled Theme

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/revanced-patches#39]
### Application

YT Revanced (Extended)

### Issue

Getting dark Theme instead of Pure Black in Notification Tile ( This is in new YT layout )

![IMG_20221028_185414](https://user-images.githubusercontent.com/93650504/198612182-580116d1-59c0-4674-a302-8be1bfbfc447.jpg)

### Patch

Solve this in next patch release...Dev's will got it.

### Motivation

For improvements in New Layout.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![ReVanced4](https://user-images.githubusercontent.com/108592928/198876128-ebb3ab20-9297-4ba8-a352-d961d2a11c72.png)

issue resolved at revanced-patches v2.99.0
