### ISSUE TITLE
feat(patch): Make MicroG Pith Black Like MicroG Lite by Chirag

### ISSUE THREAD

**Issue by AdishSagarawat** [inotia00/revanced-patches#50]
### Application

ReVanced MicroG

### Issue

This should be pitch-black

### Patch

The backgroud is dark insted of pitch black.

### Motivation

Because it looks better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
wrong place
