### ISSUE TITLE
bug: Amoled theme patch missing elements in Comments section IF "hide latest posts" is disabled.

### ISSUE THREAD

**Issue by Spacellary** [inotia00/revanced-patches#58]
### Type

Cosmetic

### Bug description

The Amoled theme patch is missing the background behind the Filter ("Top" "Newest") buttons that are present above the "Add a comment..." field IF `hide latest posts` is disabled in Revanced/Ads settings.

### Steps to reproduce

1. Disable `hide latest posts` in Revanced/Ads settings.
2. Open a video
3. Go to the comments section 

For me this was reproduced in the 3 accounts I tested. Hopefully you're also able to detect the issue.

### Screenshots or videos

<img src="https://user-images.githubusercontent.com/39604793/201490225-f0e66fd5-e620-4e32-9527-0e2e9b47ceac.jpg" width="400">

### Additional context

YouTube v17.44.34
revanced-patches v2.106.5
Device: Redmi Note 11 4G Global (spes)Android: 12 (MIUI 13)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all other requested information in this issue properly.

### Temporary fix/workaround if that happens to your account:
* Enable `hide latest posts` in Revanced/Ads settings.

**Comment by Spacellary** [comment]
### Update:

So turns out this only happens if "hide latest posts" is DISABLED in Revanced/Ads settings:

![Screenshot_2022-11-12-20-46-16-573_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201499173-4ead893c-c5f2-4710-bf4c-ab5c268433f2.jpg)

#### Looks fine if the previous option is ENABLED:

![Screenshot_2022-11-12-20-51-59-920_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201499190-870a40ff-50b2-47cc-809b-b5a823d94e6d.jpg)

**Comment by inotia00** [comment]
It took a month to completely resolve the issues you reported before (Youtube's A/B test is shit)

Since this issue is also a report that is reported only to certain users, it may take how long it will take to be completely resolved.

However, it may be good to leave an issue because there may be anyone who is experiencing the same issue.

**Comment by Spacellary** [comment]
> (YouTube's A/B test is shit)

*Truer words never spoken.*

Honestly, I was debating on closing it since enabling `hide latest posts` already kinda "solves" it for me personally, and I was aware of how much of a pain it was to fix before so I wouldn't even want this to be of any significant priority, rather you use your limited time on the more important things or wait and see if the issue shows for more people.

I agree that it's valid to leave this open as a way to concentrate the issue in a single place for when/as it is worked on.
Thanks for the great work so far.

**Comment by Spacellary** [comment]
I've found that it's not actually enabling or disabling `hide latest posts`, it's just toggling it that does it.

**Comment by inotia00** [comment]
YouTube v17.44.34
revanced-patches v2.108.0

When tested in this environment, does this still reproduce this issue?

**Comment by Spacellary** [comment]
YouTube v17.44.34
revanced-patches v2.108.0

# FIXED

Thanks for the quick work!
