### ISSUE TITLE
bug: default-video-speed setting reverts back to 2.0 if set greater than 2.0

### ISSUE THREAD

**Issue by crazdrama** [inotia00/revanced-patches#75]
### Type

Error at runtime

### Bug description

if the default speed is set to any value greater than 2.0 it does not take effect and resets back to 2.0

### Steps to reproduce

set default speed setting to anything greater than 2.0 in the revanced settings and thn try to play any video...it will only be played at 2.0

### Relevant log output

```shell
no logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The phenomenon occurs when custom-video-speed is OFF.
It is intended to prevent force close
