### ISSUE TITLE
feat(patch) Download and Fullscreen buttons

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/revanced-patches#8]
### Application

It is for download and full screen button

### Issue

Patch that make download button and Fullscreen button the same as official revanced

### Patch

Patch that make download button and Fullscreen button the same as official revanced

### Motivation

It would more beautiful if it is implemented

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohammed1520** [comment]
Is there any response 😔

**Comment by Spacellary** [comment]
Personally I like how it is now in Extended. It's very personal since it's just a cosmetic.

**Comment by inotia00** [comment]
Added `overlay-button-alternative-icon` patch in v2.82.0
